version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - ./configs/dev.env
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./configs/dev.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
    - "$SERVER_PORT:$SERVER_PORT"
volumes:
  data: